import type { WordEntry } from '$lib/types.js';

export function generateResultsHtml(words: WordEntry[], sourceFileName: string): string {
	const timestamp = new Date().toLocaleString('ja-JP');
	const rows = words
		.map(
			(w, i) =>
				`<tr>
					<td>${i + 1}</td>
					<td lang="ja">${escapeHtml(w.word)}</td>
					<td lang="ja">${escapeHtml(w.reading)}</td>
					<td>${escapeHtml(w.meaning)}</td>
					<td>${escapeHtml(w.partOfSpeech)}</td>
				</tr>`
		)
		.join('');

	return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Japanese Word Sheet — ${escapeHtml(sourceFileName)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&family=Noto+Sans:wght@400;500;700&display=swap" rel="stylesheet">
<style>
	*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
	body {
		font-family: 'Noto Sans JP', 'Noto Sans', sans-serif;
		background: #f5f5f5;
		color: #1a1a1a;
		line-height: 1.6;
		padding: 2rem;
	}
	.container { max-width: 900px; margin: 0 auto; }
	header {
		background: #fff;
		padding: 1.5rem 2rem;
		border-radius: 8px;
		box-shadow: 0 1px 3px rgba(0,0,0,0.1);
		margin-bottom: 1.5rem;
	}
	header h1 { font-size: 1.5rem; color: #333; }
	header .meta { font-size: 0.85rem; color: #666; margin-top: 0.25rem; }
	.actions { text-align: right; margin-bottom: 1rem; }
	.actions button {
		padding: 0.5rem 1.25rem;
		font-size: 0.9rem;
		border: 1px solid #ccc;
		border-radius: 6px;
		background: #fff;
		cursor: pointer;
		font-family: inherit;
	}
	.actions button:hover { background: #eee; }
	table {
		width: 100%;
		border-collapse: collapse;
		background: #fff;
		border-radius: 8px;
		overflow: hidden;
		box-shadow: 0 1px 3px rgba(0,0,0,0.1);
	}
	thead { background: #1a73e8; color: #fff; }
	th, td { padding: 0.75rem 1rem; text-align: left; }
	th { font-weight: 600; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; }
	tbody tr:nth-child(even) { background: #f8f9fa; }
	tbody tr:hover { background: #e8f0fe; }
	td:first-child { color: #999; font-size: 0.85rem; width: 2.5rem; }
	footer {
		text-align: center;
		font-size: 0.8rem;
		color: #999;
		margin-top: 2rem;
	}
	@media print {
		.actions { display: none; }
		body { background: #fff; padding: 0; }
		table { box-shadow: none; }
	}
	@media (max-width: 600px) {
		body { padding: 1rem; }
		th, td { padding: 0.5rem 0.5rem; font-size: 0.85rem; }
	}
</style>
</head>
<body>
<div class="container">
	<header>
		<h1>Japanese Word Sheet</h1>
		<p class="meta">Source: ${escapeHtml(sourceFileName)} &mdash; Generated: ${escapeHtml(timestamp)} &mdash; ${words.length} words found</p>
	</header>
	<div class="actions"><button onclick="window.print()">Print</button></div>
	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Word</th>
				<th>Reading</th>
				<th>Meaning</th>
				<th>Part of Speech</th>
			</tr>
		</thead>
		<tbody>
			${rows}
		</tbody>
	</table>
	<footer>Generated by Japanese Word Sheet Parser</footer>
</div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
	return text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#039;');
}
